/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/action-proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Action Proposals */
        get: operations["list_action_proposals_action_proposals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/action-proposals/{proposal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Action Proposal */
        get: operations["get_action_proposal_action_proposals__proposal_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit Action Proposal */
        patch: operations["edit_action_proposal_action_proposals__proposal_id__patch"];
        trace?: never;
    };
    "/action-proposals/{proposal_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Action Proposal */
        post: operations["approve_action_proposal_action_proposals__proposal_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/action-proposals/{proposal_id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Action Proposal */
        post: operations["execute_action_proposal_action_proposals__proposal_id__execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/action-proposals/{proposal_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Action Proposal */
        post: operations["reject_action_proposal_action_proposals__proposal_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/dev-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dev Login */
        post: operations["dev_login_auth_dev_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/briefs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Brief Versions */
        get: operations["list_brief_versions_briefs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/briefs/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Brief */
        post: operations["generate_brief_briefs_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/briefs/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Latest Brief */
        get: operations["get_latest_brief_briefs_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/briefs/{brief_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Brief */
        get: operations["get_brief_briefs__brief_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Demo */
        post: operations["start_demo_demo_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_me_patch"];
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Signals */
        get: operations["list_signals_signals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/signals/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract Signals */
        post: operations["extract_signals_signals_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Source Items */
        get: operations["list_source_items_source_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionExecutionResponse */
        ActionExecutionResponse: {
            action_type: components["schemas"]["ActionType"];
            /** Approval Binding Hash */
            approval_binding_hash: string;
            /** Completed At */
            completed_at: string | null;
            /** Error Code */
            error_code: string | null;
            executed_payload: components["schemas"]["TypedActionPayload"];
            /** Executed Payload Hash */
            executed_payload_hash: string;
            /** Id */
            id: string;
            /** Idempotency Key */
            idempotency_key: string;
            /** Outcome */
            outcome: string;
            /** Proposal Version */
            proposal_version: number;
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
        };
        /** ActionProposalListResponse */
        ActionProposalListResponse: {
            /** Count */
            count: number;
            /** Proposals */
            proposals: components["schemas"]["ActionProposalResponse"][];
        };
        /** ActionProposalResponse */
        ActionProposalResponse: {
            action_type: components["schemas"]["ActionType"];
            approval: components["schemas"]["ApprovalPreview"] | null;
            /** Audit Events */
            audit_events: components["schemas"]["ProposalAuditEvent"][];
            /** Confidence */
            confidence: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Evidence */
            evidence: components["schemas"]["ProposalEvidence"][];
            execution: components["schemas"]["ActionExecutionResponse"] | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Id */
            id: string;
            /** Origin Fingerprint */
            origin_fingerprint: string;
            payload: components["schemas"]["TypedActionPayload"];
            /** Payload Hash */
            payload_hash: string;
            /** Rationale */
            rationale: string;
            /** Rejection Reason */
            rejection_reason: string | null;
            risk_level: components["schemas"]["RiskLevel"];
            /**
             * Simulation Only
             * @default true
             */
            simulation_only: boolean;
            /** Source Refs */
            source_refs: string[];
            status: components["schemas"]["ProposalStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /**
         * ActionType
         * @description Closed set of proposable actions. High-risk actions (send email,
         *     delete event, purchase) are prohibited in the MVP and intentionally
         *     absent — they cannot be proposed, approved, or executed.
         * @enum {string}
         */
        ActionType: "create_task" | "create_gmail_draft" | "create_calendar_event";
        /** ApprovalPreview */
        ApprovalPreview: {
            action_type: components["schemas"]["ActionType"];
            /**
             * Approved At
             * Format: date-time
             */
            approved_at: string;
            /** Binding Hash */
            binding_hash: string;
            payload: components["schemas"]["TypedActionPayload"];
            /** Payload Hash */
            payload_hash: string;
            /** Proposal Version */
            proposal_version: number;
        };
        /** BriefEvidence */
        BriefEvidence: {
            /** Excerpt */
            excerpt: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Sender Or Organiser */
            sender_or_organiser: string | null;
            /** Source Item Id */
            source_item_id: string | null;
            /** Source Ref */
            source_ref: string;
            /** Source Type */
            source_type: string;
            /** Title */
            title: string;
        };
        /** BriefItem */
        BriefItem: {
            /** Actionable */
            actionable: boolean;
            /** Confidence */
            confidence: number;
            /** Due At */
            due_at: string | null;
            /** Evidence */
            evidence: components["schemas"]["BriefEvidence"][];
            /** Priority Band */
            priority_band: string;
            /** Priority Score */
            priority_score: number;
            /** Reason Codes */
            reason_codes: string[];
            /** Signal Id */
            signal_id: string;
            /** Signal Type */
            signal_type: string;
            /** Suggested Action */
            suggested_action: string | null;
            /** Summary */
            summary: string;
            /** Title */
            title: string;
        };
        /** BriefNotice */
        BriefNotice: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** BriefResponse */
        BriefResponse: {
            /**
             * Briefing Date
             * Format: date-time
             */
            briefing_date: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Generation Metadata */
            generation_metadata: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /** Notices */
            notices: components["schemas"]["BriefNotice"][];
            /** Prompt Version */
            prompt_version: string | null;
            /** Sections */
            sections: components["schemas"]["BriefSection"][];
            /** Source Window */
            source_window: string;
            status: components["schemas"]["BriefStatus"];
            /** Summary */
            summary: string;
            /** Version */
            version: number;
        };
        /** BriefSection */
        BriefSection: {
            /** Items */
            items: components["schemas"]["BriefItem"][];
            key: components["schemas"]["BriefSectionKey"];
            /** Label */
            label: string;
        };
        /**
         * BriefSectionKey
         * @enum {string}
         */
        BriefSectionKey: "needs_attention" | "today_upcoming" | "waiting_for" | "suggested_actions" | "low_confidence_review";
        /**
         * BriefStatus
         * @description Honest generation states surfaced to the user (skill §12).
         *
         *     complete — sections composed from persisted signals.
         *     empty — generation ran but there were no signals to report.
         *     degraded — optional LLM prose failed or was rejected; the deterministic
         *     fallback summary is shown. Facts are unaffected (they never come from
         *     the LLM).
         *     partial — one or more configured sources are unavailable, a persisted
         *     signal was omitted because its source evidence could not be resolved, or
         *     an action-proposal candidate was skipped because its source data could
         *     not be validated.
         * @enum {string}
         */
        BriefStatus: "complete" | "empty" | "degraded" | "partial";
        /** BriefVersionListResponse */
        BriefVersionListResponse: {
            /** Briefs */
            briefs: components["schemas"]["BriefVersionResponse"][];
            /** Count */
            count: number;
        };
        /** BriefVersionResponse */
        BriefVersionResponse: {
            /**
             * Briefing Date
             * Format: date-time
             */
            briefing_date: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Id */
            id: string;
            status: components["schemas"]["BriefStatus"];
            /** Version */
            version: number;
        };
        /** CalendarEventCreatePayload */
        CalendarEventCreatePayload: {
            /** Attendees */
            attendees: string[];
            /** Description */
            description: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Location */
            location: string | null;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Timezone */
            timezone: string;
            /** Title */
            title: string;
        };
        /** DemoStartResponse */
        DemoStartResponse: {
            /** Imported */
            imported: number;
            /** Skipped */
            skipped: number;
            /** Updated */
            updated: number;
        };
        /** DevLoginRequest */
        DevLoginRequest: {
            /**
             * Display Name
             * @default Dev User
             */
            display_name: string;
            /**
             * Email
             * Format: email
             * @default dev@lifeflow.local
             */
            email: string;
        };
        /** ExtractionResponse */
        ExtractionResponse: {
            /** Deterministic */
            deterministic: number;
            /** Llm Added */
            llm_added: number;
            /** Llm Failed */
            llm_failed: boolean;
            /** Llm Rejected */
            llm_rejected: number;
            /** Llm Used */
            llm_used: boolean;
            /** Persisted New */
            persisted_new: number;
            /** Persisted Unchanged */
            persisted_unchanged: number;
            /** Persisted Updated */
            persisted_updated: number;
        };
        /** GmailDraftCreatePayload */
        GmailDraftCreatePayload: {
            /** Body */
            body: string;
            /** Subject */
            subject: string;
            /** Thread Id */
            thread_id: string | null;
            /** To */
            to: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthStatus */
        HealthStatus: {
            /** Status */
            status: string;
        };
        /** MeResponse */
        MeResponse: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Id */
            id: string;
            /** Locale */
            locale: string;
            /** Onboarding State */
            onboarding_state: string;
            /** Timezone */
            timezone: string;
        };
        /** MeUpdateRequest */
        MeUpdateRequest: {
            /** Locale */
            locale?: string | null;
            onboarding_state?: components["schemas"]["OnboardingState"] | null;
            /** Timezone */
            timezone?: string | null;
        };
        /**
         * OnboardingState
         * @enum {string}
         */
        OnboardingState: "new" | "in_progress" | "complete";
        /** ProposalApprovalRequest */
        ProposalApprovalRequest: {
            action_type: components["schemas"]["ActionType"];
            /** Displayed Payload Hash */
            displayed_payload_hash: string;
            /** Expected Version */
            expected_version: number;
        };
        /** ProposalAuditEvent */
        ProposalAuditEvent: {
            /** Actor */
            actor: string;
            /** Event Type */
            event_type: string;
            /** Safe Metadata */
            safe_metadata: {
                [key: string]: unknown;
            };
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** ProposalEditRequest */
        ProposalEditRequest: {
            action_type: components["schemas"]["ActionType"];
            /** Expected Version */
            expected_version: number;
            /** Payload */
            payload: components["schemas"]["TaskCreatePayload"] | components["schemas"]["GmailDraftCreatePayload"] | components["schemas"]["CalendarEventCreatePayload"];
        };
        /** ProposalEvidence */
        ProposalEvidence: {
            /** Excerpt */
            excerpt: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Sender Or Organiser */
            sender_or_organiser: string | null;
            /** Source Item Id */
            source_item_id: string;
            /** Source Ref */
            source_ref: string;
            /** Source Type */
            source_type: string;
            /** Title */
            title: string;
        };
        /** ProposalRejectionRequest */
        ProposalRejectionRequest: {
            /** Expected Version */
            expected_version: number;
            /** Reason */
            reason?: string | null;
        };
        /**
         * ProposalStatus
         * @enum {string}
         */
        ProposalStatus: "proposed" | "edited" | "approved" | "rejected" | "executing" | "executed" | "failed" | "expired";
        /**
         * RiskLevel
         * @enum {string}
         */
        RiskLevel: "low" | "medium";
        /** SessionResponse */
        SessionResponse: {
            /** Email */
            email: string;
            /** User Id */
            user_id: string;
        };
        /** SignalListResponse */
        SignalListResponse: {
            /** Count */
            count: number;
            /** Signals */
            signals: components["schemas"]["SignalResponse"][];
        };
        /** SignalResponse */
        SignalResponse: {
            /** Confidence */
            confidence: number;
            /** Due At */
            due_at: string | null;
            /** Evidence Refs */
            evidence_refs: string[];
            /** Extraction Version */
            extraction_version: string;
            /** Id */
            id: string;
            /** Priority Band */
            priority_band: string | null;
            /** Priority Score */
            priority_score: number | null;
            /** Reason Codes */
            reason_codes: string[];
            /** Signal Type */
            signal_type: string;
            /** Summary */
            summary: string;
            /** Title */
            title: string;
        };
        /** SourceItemListResponse */
        SourceItemListResponse: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["SourceItemResponse"][];
        };
        /** SourceItemResponse */
        SourceItemResponse: {
            /** External Id */
            external_id: string;
            /** Id */
            id: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Sender Or Organiser */
            sender_or_organiser: string | null;
            /** Source Type */
            source_type: string;
            /** Title */
            title: string;
        };
        /**
         * SourceType
         * @enum {string}
         */
        SourceType: "email" | "calendar_event" | "internal_task";
        /** TaskCreatePayload */
        TaskCreatePayload: {
            /** Due At */
            due_at: string | null;
            /** Notes */
            notes: string;
            /** Title */
            title: string;
        };
        TypedActionPayload: components["schemas"]["TaskCreatePayload"] | components["schemas"]["GmailDraftCreatePayload"] | components["schemas"]["CalendarEventCreatePayload"];
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_action_proposals_action_proposals_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ProposalStatus"][] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionProposalListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_action_proposal_action_proposals__proposal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionProposalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_action_proposal_action_proposals__proposal_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalEditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionProposalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_action_proposal_action_proposals__proposal_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionProposalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_action_proposal_action_proposals__proposal_id__execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionProposalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_action_proposal_action_proposals__proposal_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalRejectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionProposalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dev_login_auth_dev_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_brief_versions_briefs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefVersionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_brief_briefs_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefResponse"];
                };
            };
        };
    };
    get_latest_brief_briefs_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefResponse"];
                };
            };
        };
    };
    get_brief_briefs__brief_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brief_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_demo_demo_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoStartResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    get_me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    update_me_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            /** @description A dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_signals_signals_get: {
        parameters: {
            query?: {
                band?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_signals_signals_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionResponse"];
                };
            };
        };
    };
    list_source_items_source_items_get: {
        parameters: {
            query?: {
                source_type?: components["schemas"]["SourceType"] | null;
                occurring_after?: string | null;
                occurring_before?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceItemListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
