#!/usr/bin/env python3
"""Regenerate the repository metrics dashboard (docs/delivery/metrics.md).

Run from the repository root:

    python3 scripts/metrics.py

Counts files and tests, measures backend coverage via pytest-cov, and reads
stage progress from docs/delivery/stage-plan.md. Requires the backend
environment (uv) and, for test/coverage numbers, the dev database when
integration tests are included. Standard library only.
"""

import json
import re
import subprocess
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOTAL_STAGES = 12  # stages 0-11

EXCLUDED_DIRS = {
    ".venv",
    "node_modules",
    ".next",
    ".next-dev",
    "__pycache__",
    ".git",
    ".ruff_cache",
    ".pytest_cache",
    ".mypy_cache",
    "coverage",
    "htmlcov",
}


def count_files(bases: list[str], suffixes: tuple[str, ...]) -> int:
    total = 0
    for base in bases:
        base_path = ROOT / base
        if not base_path.exists():
            continue
        for path in base_path.rglob("*"):
            if any(part in EXCLUDED_DIRS for part in path.parts):
                continue
            if path.suffix in suffixes and path.is_file():
                total += 1
    return total


def run(cmd: list[str], cwd: Path) -> tuple[int, str]:
    result = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    return result.returncode, result.stdout + result.stderr


def backend_tests_and_coverage() -> tuple[str, str]:
    """Return (test summary, coverage %) from a real pytest-cov run."""
    api = ROOT / "apps" / "api"
    rc, out = run(["uv", "run", "pytest", "-q", "--cov=lifeflow_api", "--cov-report=term"], api)
    if rc != 0:
        # Integration tests need the db container; fall back and say so.
        rc, out = run(["uv", "run", "pytest", "-q", "-m", "not integration",
                       "--cov=lifeflow_api", "--cov-report=term"], api)
        suffix = " (integration tests skipped — start the db for the full number)"
    else:
        suffix = ""
    passed = re.search(r"(\d+) passed", out)
    total_line = re.search(r"TOTAL\s+\d+\s+\d+\s+(\d+)%", out)
    tests = f"{passed.group(1)} passing{suffix}" if passed else "unavailable (pytest failed)"
    coverage = f"{total_line.group(1)}%" if total_line else "unavailable"
    return tests, coverage


def web_tests() -> str:
    rc, out = run(["pnpm", "--filter", "@lifeflow/web", "test"], ROOT)
    match = re.search(r"Tests\s+(\d+) passed", out)
    return f"{match.group(1)} passing" if rc == 0 and match else "unavailable (vitest failed)"


def ci_status() -> str:
    """Report whether GitHub Actions workflows are actually wired in.

    Previously a hardcoded "not yet connected" placeholder that was never
    updated once CI genuinely started running — a stale-metrics defect found
    during the Stage 9 Final Integration audit. Reflects the repository
    state (workflow files present), not live run status, since this script
    has no network access to query Actions.
    """
    workflows_dir = ROOT / ".github" / "workflows"
    if not workflows_dir.is_dir():
        return "not yet connected — no .github/workflows directory"
    names = sorted(p.name for p in workflows_dir.glob("*.yml"))
    if not names:
        return "not yet connected — no workflow files"
    return f"connected — {', '.join(names)}"


def stage_progress() -> tuple[str, str]:
    text = (ROOT / "docs" / "delivery" / "stage-plan.md").read_text(encoding="utf-8")
    active = re.search(r"\*\*Status:\*\*\s*Stage (\d+)", text)
    current = active.group(1) if active else "?"
    approved = len(re.findall(r"\(approved\)", text))
    pending = " (+1 complete pending approval)" if "complete pending approval" in text else ""
    return current, f"{approved}/{TOTAL_STAGES}{pending}"


def main() -> int:
    py_files = count_files(["apps/api", "workers", "scripts"], (".py",))
    ts_files = count_files(["apps/web/src", "packages"], (".ts", ".tsx"))
    prompt_files = count_files(["prompts"], (".md",)) - 1  # exclude prompts/README.md
    eval_cases = sum(
        len(json.loads(path.read_text())["cases"])
        for path in ROOT.glob("evals/golden/*/cases.json")
    )
    api_tests, api_coverage = backend_tests_and_coverage()
    web = web_tests()
    e2e_specs = sum(
        len(re.findall(r"^test\(", path.read_text(), re.M))
        for e2e_dir in ("apps/web/e2e", "apps/web/e2e-resilience")
        if (ROOT / e2e_dir).exists()
        for path in (ROOT / e2e_dir).glob("*.spec.ts")
    )
    ci = ci_status()
    current_stage, completed = stage_progress()

    doc = f"""# Repository Metrics

**Generated by `python3 scripts/metrics.py` on {date.today().isoformat()} — do not hand-edit; rerun the script.**

| Metric | Value |
|---|---|
| Python files | {py_files} |
| TypeScript files | {ts_files} |
| Prompt files | {max(prompt_files, 0)} |
| Eval cases | {eval_cases} |
| Backend tests | {api_tests} |
| Backend coverage | {api_coverage} |
| Frontend tests | {web} |
| E2E journeys (Playwright) | {e2e_specs} |
| Frontend coverage | not yet measured — coverage reporter deferred until the UI stabilises |
| CI | {ci} |
| Current stage | {current_stage} |
| Approved stages | {completed} |

Stage detail: [stage-plan.md](stage-plan.md). Quality-gate evidence lives in each stage completion report.
"""
    (ROOT / "docs" / "delivery" / "metrics.md").write_text(doc, encoding="utf-8")
    print(doc)
    return 0


if __name__ == "__main__":
    sys.exit(main())
