"""signal priority columns (skill §8: explainable score, reason codes, dedupe).

Safe on existing databases: no writer of the signals table existed before this
revision, so the NOT NULL additions apply to an empty table.

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-16 00:35:56.023183

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("signals", sa.Column("priority_score", sa.Float(), nullable=True))
    op.add_column("signals", sa.Column("priority_band", sa.String(length=10), nullable=True))
    op.add_column("signals", sa.Column("reason_codes", sa.JSON(), nullable=False))
    op.add_column("signals", sa.Column("dedupe_key", sa.String(length=64), nullable=False))
    op.create_unique_constraint("uq_signals_user_dedupe", "signals", ["user_id", "dedupe_key"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_signals_user_dedupe", "signals", type_="unique")
    op.drop_column("signals", "dedupe_key")
    op.drop_column("signals", "reason_codes")
    op.drop_column("signals", "priority_band")
    op.drop_column("signals", "priority_score")
    # ### end Alembic commands ###
